image: microsoft/powershell:latest

stages:
    - deploy

deploy to psgallery:
    stage: deploy
    when: manual
    only: 
        - /^v\d.*$/
    except:
        - branches
    script:
        - pwsh -NoProfile -NoLogo ./publish.ps1 -Version "$Env:CI_COMMIT_TAG" -NuGetApiKey "$Env:NUGET_API_KEY"
